### PR TITLE
Optionally provide additional stop sequence on per completion basis

### PR DESCRIPTION
**Pull request by henke443**
Could not help myself, now I really have to sleep good night :)
Also edited readme slightly.

### CODE REVIEW

**Comment by VincentHch** [comment]
I'm not comfortable with this feature. Firstly it add an input, and then you can only add keyword so that means you must remove them from the settings and add the "def", "@" or "class" every time you want a function completion (most of the time I guess, given that codex is not really reliable for writing multiple functions at the same time).


I think there are only 3 use case:

- predict a **function**: keywords are "def", "class" and "@"
- predict a **class**: keywords are "class"
- predict a **code snippet**: no keywords.

It should be great to have different level (block/function/class/file), each level are defined in the settings and we could have a *quick pick* (`showQuickPick` in the API) requested for a second key mapping (ex: ctrl+shift+enter)

**Comment by henke443** [comment]
I understand, the stop sequence is not added to the settings though it's just temporary. It might be useful when programming in other languages or when you want to generate short snippets not necessarily a whole function or class. It was very late when I made the PR, I should've made it another command maybe.

**Comment by henke443** [comment]
I'm working on a refactor command right now which you might like more. I can make a new PR in which I add the ability to specify temporary stop with a new keybind maybe? If not no hard feelings ;)

**Comment by VincentHch** [comment]
Don't you think the quick pick could be easier ? We could indeed add a pick "custom stop sequence", leading to a new input in which user specify its own command.
The ideal feature would be to have differents settings for each langages, but its not worth it as user will mainly focus on a single langage.

**Comment by VincentHch** [comment]
There are generaly one langage per project, therefore users can specify the stop sequences in the `.vscode/settings.json`.

**Comment by VincentHch** [comment]
You can propose your solution here: #7

**Comment by VincentHch** [comment]
@henke443 I've just pushed a new feature based on your idea, I'm closing this PR as stop sequences have been implemented in my last commit

**Pull request closed without merging**
